hmcts/rpts-api

.github/renovate.json, build.gradle
https://tools.hmcts.net/jira/browse/FACT-1103
Testing renovate
```
[ ] Yes
[x] No
```
=> FACT-1103: Testing renovate

build.gradle, charts/rpts-api/Chart.yaml, charts/rpts-api/values.preview.template.yaml, charts/rpts-api/values.yaml, docker-compose.yml, docker/database/Dockerfile, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf, src/main/resources/application.yaml
=> updating db

Dockerfile, charts/rpts-api/Chart.yaml, charts/rpts-api/values.yaml, src/main/resources/application.yaml, src/smokeTest/resources/logback-includes.xml
=> updating app insights config

src/main/resources/application.yaml
=> adding db to health check

charts/rpts-api/Chart.yaml, charts/rpts-api/values.preview.template.yaml
=> changing preview username

Dockerfile, build.gradle
=> java 17 changes

.gitignore, build.gradle, charts/rpts-api/Chart.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/rpts/controllers/AddressController.java, src/main/java/uk/gov/hmcts/reform/rpts/controllers/RootController.java, src/main/resources/application.yaml
Adding rate limiting
```
[ ] Yes
[ x] No
```
=> adding rate limiting

infrastructure/main.tf, infrastructure/variables.tf
Fix location error
```
[ ] Yes
[x ] No
```
=> changes to location for appinsights

build.gradle, infrastructure/main.tf
CVE fixes
```
[ ] Yes
[ ] No
```
=> CVE updates

charts/rpts-api/Chart.yaml, charts/rpts-api/values.yaml
Changes to config for rpts for flex server
=> changes to configt

charts/rpts-api/Chart.yaml, charts/rpts-api/values.yaml
=> changes to config to get past mig error for now

charts/rpts-api/Chart.yaml, charts/rpts-api/values.yaml
=> changes to ingress host which is outdated

charts/rpts-api/values.yaml
=> reverting change

infrastructure/main.tf
=> removing ss secrets and v11 pg

build.gradle, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties
=> build gradle updates

build.gradle
=> versions update

.github/workflows/ci.yml, .github/workflows/codeql.yml, Jenkinsfile_CNP, build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/rpts/config/SwaggerPublisherTest.java, src/main/java/uk/gov/hmcts/reform/rpts/controllers/AddressController.java, src/main/java/uk/gov/hmcts/reform/rpts/entities/Nspl.java, src/main/java/uk/gov/hmcts/reform/rpts/entities/NsplHistory.java, src/test/java/uk/gov/hmcts/reform/rsecheck/controllers/AddressControllerTest.java
=> springboot 3 updates

Dockerfile, build.gradle, charts/rpts-api/Chart.yaml, charts/rpts-api/values.yaml, lib/applicationinsights.json
Fix app insights.
```
[ ] Yes
[x] No
```
=> FACT-1723 fix app insights

.github/workflows/publish-openapi.yaml
https://tools.hmcts.net/jira/browse/FACT-1792
Fix open API publishing
```
[ ] Yes
[x] No
```
=> FACT-1792 - open API

README.md
https://tools.hmcts.net/jira/browse/FACT-1679
added contents
added new subsections about NSPL and OS data
```
[ ] Yes
[x] No
```
=> FACT-1679 readme update

build.gradle
https://tools.hmcts.net/jira/browse/FACT-1947
cve fixes
=> FACT-1947 update CVEs

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> FACT-2292 dependancies
